[[pages]]
path = "app/pages/_home.py"
name = "Home"
icon = "ğŸ¡"

[[pages]]
path = "app/pages/01_core_report.py"
name = "Core Report"
icon = "ğŸ“Š"

[[pages]]
path = "app/pages/02_labor.py"
name = "Labor"
icon = "ğŸ‘¨â€ğŸ­"

[[pages]]
path = "app/pages/03_debt.py"
name = "Debt"
icon = "ğŸ§¾"
